management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/employee/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
  profiles:
    active: native
  config:
    import: optional:configserver:http://config-service:8888